import * as mongoose from 'mongoose';

// Define a schema for the Job model
export const JobSchema = new mongoose.Schema({
  // 'title' is a required field of type String
  title: { type: String, required: true },

  // 'description' is a required field of type String
  description: { type: String, required: true },

  // 'salary' is a required field of type Number
  salary: { type: Number, required: true },
});

// Define a TypeScript interface for the Job model
export interface Job extends mongoose.Document {
  // 'id' represents the unique identifier for each job (automatically generated by MongoDB)
  id: string;

  // 'title' is the job title (a string)
  title: string;

  // 'description' is the job description (a string)
  description: string;

  // 'salary' is the job salary (a number)
  salary: number;
}
